spring:
  application:
    name: indexador_sentencas_militares

opensearch:
  host: ${OPENSEARCH_HOST:127.0.0.1}
  port: ${OPENSEARCH_PORT:9200}
  scheme: ${OPENSEARCH_SCHEME:http}
  username: ${OPENSEARCH_USERNAME:admin}
  password: ${OPENSEARCH_PASSWORD:admin}
  
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://sso.stg.cloud.pje.jus.br/auth/realms/pje/protocol/openid-connect/token}
  client-id: ${KEYCLOAK_CLIENT_ID:banco-sentencas}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:eFArtoaEyh8GYfQPXLZgGKiFG3VTDovR}

datalake-processos-api:
  base-url: ${DATALAKE_PROCESSOS_API_BASE_URL:https://api-processo.stg.data-lake.pdpj.jus.br/processo-api/api/v1/processos}
